// ─── Notification Domain Types (zero external dependencies) ──────────────────

/** All supported delivery channels */
export type NotificationChannel = 'email' | 'push' | 'sms';

/** Template IDs — each maps to a renderer + subject */
export type NotificationTemplate =
  // Auth / Security (operational group — always sent)
  | 'otp'
  | 'new_device_login'
  | 'password_changed'
  | 'password_reset'
  // Registration (operational group — always sent)
  | 'welcome_live'
  | 'welcome_demo'
  // Account / Trading alerts (alerts group — user can opt out)
  | 'auto_cutoff'
  | 'margin_call'
  | 'deposit_approved'
  | 'withdrawal_approved'
  | 'withdrawal_rejected'
  // Admin announcements (marketing group — user can opt out)
  | 'announcement';

export type NotificationPriority = 'high' | 'normal' | 'low';

export type UserType = 'live' | 'demo' | 'admin';

/**
 * Template group determines whether user preferences are checked before dispatch.
 * - operational: always sent (OTPs, security notifications)
 * - alerts:      trading / financial alerts — respects user opt-out
 * - marketing:   announcements — respects user opt-out
 */
export type TemplateGroup = 'operational' | 'alerts' | 'marketing';

/** Maps each template to its group — used by NotificationService for preference checks */
export const TEMPLATE_GROUP_MAP: Record<NotificationTemplate, TemplateGroup> = {
  otp:                  'operational',
  new_device_login:     'operational',
  password_changed:     'operational',
  password_reset:       'operational',
  welcome_live:         'operational',
  welcome_demo:         'operational',
  auto_cutoff:          'alerts',
  margin_call:          'alerts',
  deposit_approved:     'alerts',
  withdrawal_approved:  'alerts',
  withdrawal_rejected:  'alerts',
  announcement:         'marketing',
};

/**
 * The canonical notification event published on Kafka topic `notification.send`.
 * Any service that needs to send a notification publishes this shape.
 */
export interface NotificationEvent {
  /**
   * Globally unique event ID — generated by the publishing service (UUID v4).
   * Used as the deduplication key: if this eventId already exists in notification_logs,
   * the dispatch is skipped (exactly-once delivery across consumer restarts).
   */
  eventId:   string;

  channel:   NotificationChannel;
  template:  NotificationTemplate;
  priority:  NotificationPriority;
  recipient: string;          // email address, FCM token, or phone number

  /**
   * The user this notification is for.
   * Optional: anonymous/system notifications may omit these.
   */
  userId?:   string;
  userType?: UserType;

  /** Template data — varies per template */
  data:      Record<string, unknown>;

  /** ISO timestamp the event was created — used for staleness check */
  createdAt?: string;

  /** BCP-47 locale for template rendering. Default: 'en' */
  locale?:    string;
}

/** Delivery result returned from a channel handler */
export interface DeliveryResult {
  success:   boolean;
  channel:   NotificationChannel;
  recipient: string;
  error?:    string;
}
